services:
  postgres:
    image: postgres:15
    container_name: shipyard-postgres
    environment:
      POSTGRES_USER: shipyard
      POSTGRES_PASSWORD: shipyard_db_change_me
      POSTGRES_DB: shipyard
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: shipyard-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: shipyard_minio
      MINIO_ROOT_PASSWORD: shipyard_minio_change_me
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    build: .
    container_name: shipyard-api 
    command: ./api
    environment:
      DATABASE_URL: postgres://shipyard:shipyard_db_change_me@postgres:5432/shipyard?sslmode=disable
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: shipyard_minio
      MINIO_SECRET_KEY: shipyard_minio_change_me
      MINIO_BUCKET: deployments
      SHIPYARD_API_KEY: shipyard_api_key_change_me_please
      SHIPYARD_RATE_LIMIT_PER_MINUTE: 60
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - minio

  worker:
    build: .
    container_name: shipyard-worker
    command: ./worker
    environment:
      DATABASE_URL: postgres://shipyard:shipyard_db_change_me@postgres:5432/shipyard?sslmode=disable
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: shipyard_minio
      MINIO_SECRET_KEY: shipyard_minio_change_me
      MINIO_BUCKET: deployments
      BUILDER_IMAGE: node:20
      MAX_REPO_SIZE_MB: 200
      MAX_BUILD_TIME_MINUTES: 10
      MAX_CONCURRENT_BUILDS: 1
      MAX_LOG_SIZE_BYTES: 8192

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      - postgres
      - minio

  nginx:
    image: nginx
    container_name: shipyard-nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      
